---
title: 'Final Project: Guidance Document and Checksheet'
author: "Tsu-yen Su"
date: "Due June 26, 2023"
output:  html_notebook
---

nts


### Data Access

(A) .Rmd Line numbers where at least two different data sources are imported:  

##Line 24-47

(B) .Rmd Line numbers for inspecting data intake:  

## Line 51-75

### Data Wrangling (5 out of 7 required)

(A) .Rmd Line number(s) for general data wrangling: 

## Line 89-91

(B) .Rmd Line number(s) for a join operation: 

## Line 97-115

(C) .Rmd Line number(s) for use of reduction and/or transformation functions: 

## Line 121-124

(D) .Rmd Line number(s) for a pivot_wider or pivot_longer operation (or equivalent):

## Line 132-147

(E) .Rmd Line number(s) for use of regular expressions: 


(F) .Rmd Line number(s) for use of user-defined functions: 


(G) .Rmd Line number(s) for use of loops and/or control flow: 

## Line 153-184
  

### Data Visualization (3 of 5 required)

(A) .Rmd Line number(s) for use of multiple different geoms on a single plot:  

## Line 199-208 

(B) .Rmd Line number(s) for use of multiple aesthetics: 

## Line 220-225 

(C) .Rmd Line number(s) for use of layered graphics:  

## Line 233-242 
(D) .Rmd Line number(s) for use of maps:  

(E) .Rmd Line number(s) for use of decision tree or dendogram:    









